before_install: gem update bundler
env: RAKE_TASK=spec
language: ruby
matrix:
  include:
  - gemfile: gemfiles/activemodel3.rb
    rvm: 2.2
rvm:
- 2.2
- 2.1
- 2.0
- 1.9
- rbx-2
script: bundle exec rake $RAKE_TASK
